name: Node.js Package
on:
  release:
    types: [created]
  push: { branches: [main] }
env:
  TAG: latest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - run: npm version ${{ github.run_id }} && echo "::set-env name=TAG::vnext"
        if: github.ref == 'refs/heads/main'
      - run: npm publish --tag $TAG
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
